defaults: &defaults
  options:

development:
  <<: *defaults
  sessions:
    default:
      database: storycafe_simple_development
      hosts:
        - localhost:27017

test:
  <<: *defaults
  sessions:
    default:
      database: storycafe_simple_test 
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0

production:
  <<: *defaults
  sessions:
    default:
      database: storycafe_simple_production
      hosts: 
        - localhost:27017
